#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7CD755928F8AE51A34E40E9B7293A7331ADFF327583A515FC0915B67819293AE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;
using WPFFirstApp;


namespace WPFFirstApp {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : Tekla.Structures.Dialog.ApplicationWindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 38 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label;
        
        #line default
        #line hidden
        
        
        #line 44 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_Copy;
        
        #line default
        #line hidden
        
        
        #line 50 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_material;
        
        #line default
        #line hidden
        
        
        #line 62 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox;
        
        #line default
        #line hidden
        
        
        #line 75 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_Copy;
        
        #line default
        #line hidden
        
        
        #line 82 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfProfileCatalog profileCatalog;
        
        #line default
        #line hidden
        
        
        #line 96 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox materialBox;
        
        #line default
        #line hidden
        
        
        #line 104 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog materialCatalog;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFFirstApp;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.label = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.label_Copy = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.label_material = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.textBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.textBox_Copy = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.profileCatalog = ((Tekla.Structures.Dialog.UIControls.WpfProfileCatalog)(target));
            
            #line 86 "MainWindow.xaml"
            this.profileCatalog.SelectClicked += new System.EventHandler(this.profileCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 87 "MainWindow.xaml"
            this.profileCatalog.SelectionDone += new System.EventHandler(this.profileCatalog_SelectionDone);
            
            #line default
            #line hidden
            return;
            case 7:
            this.materialBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.materialCatalog = ((Tekla.Structures.Dialog.UIControls.WpfMaterialCatalog)(target));
            
            #line 108 "MainWindow.xaml"
            this.materialCatalog.SelectClicked += new System.EventHandler(this.materialCatalog_SelectClicked);
            
            #line default
            #line hidden
            
            #line 109 "MainWindow.xaml"
            this.materialCatalog.SelectionDone += new System.EventHandler(this.materialCatalog_SelectionDone_1);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 122 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkCreateCancel)(target)).CancelClicked += new System.EventHandler(this.WPFOkCreateCancel_CancelClicked);
            
            #line default
            #line hidden
            
            #line 123 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkCreateCancel)(target)).CreateClicked += new System.EventHandler(this.WPFOkCreateCancel_CreateClicked);
            
            #line default
            #line hidden
            
            #line 124 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkCreateCancel)(target)).OkClicked += new System.EventHandler(this.WPFOkCreateCancel_OkClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

